### PR TITLE
font-size + title

### PR DESCRIPTION
**Pull request by diomed**
bigger font size + title in head
specified doctype

### CODE REVIEW

**Comment by diomed** [comment]
please enable github pages, and put link to it in website area of main repo

**Comment by diomed** [comment]
⁉️

**Comment by jamesknelson** [comment]
I'm not willing to change the font size, sorry - it'd break the layout when printing, which is the main point of this cheatsheet.

**Comment by diomed** [comment]
I see your point, and I raise you a css media query for printing:

```
@media print {
   font-size: 8pt;
}
```
which allows font to stay smaller when printing, while on page it displays bigger.

**Comment by diomed** [comment]
what do you say about that ⁉️

**Pull request closed without merging**
